#pragma once
#include <algorithm>
#include <cmath>
#include <utility>
#include <numeric>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <iostream>
#include <optional>
#include <string_view>
#include <execution>
#include <iterator>
#include <ctime>